### PR TITLE
Test lowest deps and re-add Symfony 4.4 support

### LINKED ISSUE #30: Compile Error on 3.1 update
Upon updating to 3.1 (with Symfony 4.4), I got the following compile error:
Compile Error: Declaration of OAT\Bundle\Lti1p3Bundle\DependencyInjection\S  
!!    ecurity\Factory\Message\LtiPlatformMessageSecurityFactory::create(Symfony\C  
!!    omponent\DependencyInjection\ContainerBuilder $container, string $id, array  
!!     $config, string $userProvider, ?string $defaultEntryPoint = NULL): array m  
!!    ust be compatible with Symfony\Bundle\SecurityBundle\DependencyInjection\Se  
!!    curity\Factory\SecurityFactoryInterface::create(Symfony\Component\Dependenc  
!!    yInjection\ContainerBuilder $container, $id, $config, $userProviderId, $def  
!!    aultEntryPointId)

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #30 

Cheers!

### CODE REVIEW

**Comment by ekkinox** [comment]
Hey @weaverryan !

Following my comment on https://github.com/oat-sa/bundle-lti1p3/issues/30#issuecomment-746470746, I propose to remove the type hint and open a PR. 

Could I then redirect your PR to my branch to:
- add the typehint fixes
- add your lower deps config

and release all at once ? What do you think ?

**Comment by weaverryan** [comment]
Hey @ekkinox!

I've got both of those things (I think) done on this PR. Feel free to merge it, or close it and implement the code on a different branch - I am not worried about getting proper credit or anything like that :).

Thanks!

**Comment by weaverryan** [comment]
Btw, the "lowest" tests still fail, it looks like it's likely a small, annoying "kernel setup" difference in the tests for Symfony 4 vs Symfony 5.

**Comment by ekkinox** [comment]
Oh yes I just saw you already fixed the factories, it's awesome, perfect !

Ofc you'll get the credits, you were just faster ! I'm actually glad this bundle is used other than in our projects ;)

Ok, I wait build fix then we merge yours, just I redirect your PR to develop to follow our release process if you don't mind.

**Comment by ekkinox** [comment]
also, sorry to ask you this, would you mind to add a changelog entry ? 
```
3.3.1
-----

* Fixed security factories for symfony 4.4 compatibility
```

or something like this ? I would be really nice :+1:

**Comment by weaverryan** [comment]
It looks like things are passing now, and rebased onto the target branch! This should be ready!

**Review by ekkinox — APPROVED** [review]
Amazing ! I pre-approve, still waiting build results then I release this for you. 

many thx @weaverryan for this contrib !

**Pull request merged**
